const productDatabase = {
  pain: [
    {
      id: "pain-01",
      image: process.env.PUBLIC_URL + "/images/pain01.jpg",
      title: "해피백 릴렉스넥스",
      desc: "목 부위 안정화 운동과 밸런스 훈련에 적합!",
      made: "독일",
      madeby: "TOGU",
      price: 49000,
    },
    {
      id: "pain-02",
      image: process.env.PUBLIC_URL + "/images/pain02.jpg",
      title: "PUSH 오쏘 엄지수근중수관절 보호대",
      desc: "손의 기능을 유지하고 안정화까지 한번에!",
      made: "네덜란드",
      madeby: "NEA",
      price: 95000,
    },
    {
      id: "pain-03",
      image: process.env.PUBLIC_URL + "/images/pain03.jpg",
      title: "뉴렉 워크스테이션",
      desc: "근육의 재건, 관절운동의 회복을 목적으로 하는 수동식 기기",
      made: "노르웨이",
      madeby: "redcord",
      price: 12500000,
    },
    {
      id: "pain-04",
      image: process.env.PUBLIC_URL + "/images/pain04.jpg",
      title: "스티뮬라 플러스",
      desc: "견적문의",
      made: "노르웨이",
      madeby: "redcord",
      price: 0,
    },
    {
      id: "pain-05",
      image: process.env.PUBLIC_URL + "/images/pain05.jpg",
      title: "스탠딩 스파인 코렉터",
      desc: "견적문의",
      made: "",
      madeby: "",
      price: 0,
    },
    {
      id: "pain-06",
      image: process.env.PUBLIC_URL + "/images/pain06.jpg",
      title: "씨네스포츠 미토테이블",
      desc: "견적문의",
      made: "이탈리아",
      madeby: "",
      price: 0,
    },
    {
      id: "pain-07",
      image: process.env.PUBLIC_URL + "/images/pain07.jpg",
      title: "다이나믹 에어쿠션 데코",
      desc: "올바른 자세와 안정적인 신체 밸런스를 위해!",
      made: "독일",
      madeby: "TOGU",
      price: 99000,
    },
    {
      id: "pain-08",
      image: process.env.PUBLIC_URL + "/images/pain08.jpg",
      title: "점퍼",
      desc: "안정성을 위한다면 토구점퍼와 함께 하세요",
      made: "독일",
      madeby: "TOGU",
      price: 407000,
    },
    {
      id: "pain-09",
      image: process.env.PUBLIC_URL + "/images/pain09.jpg",
      title: "멀티롤 펑셔널",
      desc: "허리와 코어 강화 훈련에 강력한 효과",
      made: "독일",
      madeby: "TOGU",
      price: 143000,
    },
    {
      id: "pain-10",
      image: process.env.PUBLIC_URL + "/images/pain10.jpg",
      title: "에어로스텝 엑스엘",
      desc: "신체 자세 평가를 바탕으로 한 자세인지 트레이닝!",
      made: "독일",
      madeby: "TOGU",
      price: 275000,
    },
    {
      id: "pain-11",
      image: process.env.PUBLIC_URL + "/images/pain11.jpg",
      title: "에어로스텝 엑스엘 펑셔널(블랙)",
      desc: "신체 자세 평가를 바탕으로 한 자세인지 트레이닝!",
      made: "독일",
      madeby: "TOGU",
      price: 275000,
    },
    {
      id: "pain-12",
      image: process.env.PUBLIC_URL + "/images/pain12.jpg",
      title: "볼란스 센스티브(흰색)",
      desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
      made: "독일",
      madeby: "TOGU",
      price: 180000,
    },
    {
      id: "pain-13",
      image: process.env.PUBLIC_URL + "/images/pain13.jpg",
      title: "볼란스 인테시브(검정)",
      desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
      made: "독일",
      madeby: "TOGU",
      price: 180000,
    },
    {
      id: "pain-14",
      image: process.env.PUBLIC_URL + "/images/pain14.jpg",
      title: "스프리트 슬링",
      desc: "레드코드 목 전용 스트랩",
      made: "노르웨이",
      madeby: "redcord",
      price: 120000,
    },
  ],

  hot: [
    {
      type: "hot",
      id: "hot-01",
      image: process.env.PUBLIC_URL + "/images/hot01.jpg",
      title: "토구 챌린지디스크 2.0",
      desc: "하체와 코어 근력강화에 탁월한 효과!",
      made: "독일",
      madeby: "TOGU",
      price: 605000,
    },
    {
      type: "hot",
      id: "hot-02",
      image: process.env.PUBLIC_URL + "/images/hot02.jpg",
      title: "점퍼",
      desc: "안정성을 위한다면 토구점퍼와 함께 하세요",
      made: "독일",
      madeby: "TOGU",
      price: 407000,
    },
    {
      type: "hot",
      id: "hot-03",
      image: process.env.PUBLIC_URL + "/images/hot03.jpg",
      title: "[레드코드]엑시스(Axis)",
      made: "독일",
      madeby: "TOGU",
      desc: "",
      price: 880000,
    },
    {
      type: "hot",
      id: "hot-04",
      image: process.env.PUBLIC_URL + "/images/hot04.jpg",
      title: "레드밸런스 밸런스패드(tpe)",
      desc: "코어운동과 균형운동에 특화!",
      made: "독일",
      madeby: "TOGU",
      price: 55000,
    },
    {
      type: "hot",
      id: "hot-05",
      image: process.env.PUBLIC_URL + "/images/hot05.jpg",
      title: "토구 필라테스볼(22cm)",
      desc: "심부근육,소근육 등 근육운동에 효과적!",
      made: "독일",
      madeby: "TOGU",
      price: 28000,
    },
    {
      type: "hot",
      id: "hot-06",
      image: process.env.PUBLIC_URL + "/images/hot06.jpg",
      title: "스모비 민트",
      desc: "신체의 모든 부위의 활성화를 위한다면 스모비!",
      made: "독일",
      madeby: "TOGU",
      price: 220000,
    },
    {
      type: "hot",
      id: "hot-07",
      image: process.env.PUBLIC_URL + "/images/hot07.jpg",
      title: "제로밴드-핑크(HARD)",
      desc: "내 몸에 맞는 운동을 다양하게!",
      made: "독일",
      madeby: "TOGU",
      price: 16500,
    },
    {
      type: "hot",
      id: "hot-08",
      image: process.env.PUBLIC_URL + "/images/hot08.jpg",
      title: "제로밴드-티파니블루(Beginner)",
      desc: "내 몸에 맞는 운동을 다양하게!",
      made: "독일",
      madeby: "TOGU",
      price: 16500,
    },
    {
      type: "hot",
      id: "hot-09",
      image: process.env.PUBLIC_URL + "/images/hot09.jpg",
      title: "다이나믹 에어쿠션 데코",
      desc: "올바른 자세를 위한 솔루션!",
      made: "독일",
      madeby: "TOGU",
      price: 99000,
    },
    {
      type: "hot",
      id: "hot-10",
      image: process.env.PUBLIC_URL + "/images/hot10.jpg",
      title: "에어로스텝 엑스엘",
      desc: "신체 자세 평가를 바탕으로 한 자세인지 트레이닝!",
      made: "독일",
      madeby: "TOGU",
      price: 275000,
    },
    {
      type: "hot",
      id: "hot-11",
      image: process.env.PUBLIC_URL + "/images/hot11.jpg",
      title: "볼란스 센스티브(흰색)",
      desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
      made: "독일",
      madeby: "TOGU",
      price: 180000,
    },
    {
      type: "hot",
      id: "hot-12",
      image: process.env.PUBLIC_URL + "/images/hot12.jpg",
      title: "볼란스 인텐시브(검정)",
      desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
      made: "독일",
      madeby: "TOGU",
      price: 180000,
    },
  ],
};

export default productDatabase;
