const hotitem = [
  {
    type: "hot",
    id: "hot-01",
    image: process.env.PUBLIC_URL + "/images/hot01.jpg",
    title: "토구 챌린지디스크 2.0",
    desc: "하체와 코어 근력강화에 탁월한 효과!",
    made: "독일",
    madeby: "TOGU",
    price: 605000,
  },
  {
    type: "hot",
    id: "hot-02",
    image: process.env.PUBLIC_URL + "/images/hot02.jpg",
    title: "점퍼",
    desc: "안정성을 위한다면 토구점퍼와 함께 하세요",
    made: "독일",
    madeby: "TOGU",
    price: 407000,
  },
  {
    type: "hot",
    id: "hot-03",
    image: process.env.PUBLIC_URL + "/images/hot03.jpg",
    title: "[레드코드]엑시스(Axis)",
    made: "독일",
    madeby: "TOGU",
    desc: "",
    price: 880000,
  },
  {
    type: "hot",
    id: "hot-04",
    image: process.env.PUBLIC_URL + "/images/hot04.jpg",
    title: "레드밸런스 밸런스패드(tpe)",
    desc: "코어운동과 균형운동에 특화!",
    made: "독일",
    madeby: "TOGU",
    price: 55000,
  },
  {
    type: "hot",
    id: "hot-05",
    image: process.env.PUBLIC_URL + "/images/hot05.jpg",
    title: "토구 필라테스볼(22cm)",
    desc: "심부근육,소근육 등 근육운동에 효과적!",
    made: "독일",
    madeby: "TOGU",
    price: 28000,
  },
  {
    type: "hot",
    id: "hot-06",
    image: process.env.PUBLIC_URL + "/images/hot06.jpg",
    title: "스모비 민트",
    desc: "신체의 모든 부위의 활성화를 위한다면 스모비!",
    made: "독일",
    madeby: "TOGU",
    price: 220000,
  },
  {
    type: "hot",
    id: "hot-07",
    image: process.env.PUBLIC_URL + "/images/hot07.jpg",
    title: "제로밴드-핑크(HARD)",
    desc: "내 몸에 맞는 운동을 다양하게!",
    made: "독일",
    madeby: "TOGU",
    price: 16500,
  },
  {
    type: "hot",
    id: "hot-08",
    image: process.env.PUBLIC_URL + "/images/hot08.jpg",
    title: "제로밴드-티파니블루(Beginner)",
    desc: "내 몸에 맞는 운동을 다양하게!",
    made: "독일",
    madeby: "TOGU",
    price: 16500,
  },
  {
    type: "hot",
    id: "hot-09",
    image: process.env.PUBLIC_URL + "/images/hot09.jpg",
    title: "다이나믹 에어쿠션 데코",
    desc: "올바른 자세를 위한 솔루션!",
    made: "독일",
    madeby: "TOGU",
    price: 99000,
  },
  {
    type: "hot",
    id: "hot-10",
    image: process.env.PUBLIC_URL + "/images/hot10.jpg",
    title: "에어로스텝 엑스엘",
    desc: "신체 자세 평가를 바탕으로 한 자세인지 트레이닝!",
    made: "독일",
    madeby: "TOGU",
    price: 275000,
  },
  {
    type: "hot",
    id: "hot-11",
    image: process.env.PUBLIC_URL + "/images/hot11.jpg",
    title: "볼란스 센스티브(흰색)",
    desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
    made: "독일",
    madeby: "TOGU",
    price: 180000,
  },
  {
    type: "hot",
    id: "hot-12",
    image: process.env.PUBLIC_URL + "/images/hot12.jpg",
    title: "볼란스 인텐시브(검정)",
    desc: "당신의 기세등등한 라이프 스타일을 위한 솔루션!",
    made: "독일",
    madeby: "TOGU",
    price: 180000,
  },
];

export default hotitem;
